{
 "title": "get-random-number",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"golang\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"golang\"}",
     "legendFormat": "Next GC"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"golang\"}",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Application Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{instance=\"host.docker.internal:8081\",job=\"golang\"})"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{job=\"golang\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "process_open_fds{job=\"golang\"}",
     "legendFormat": "Open"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(sre_test_7_http_duration_seconds_count{path='/get-random-number'}[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Time spent in HTTP requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(sre_test_7_http_duration_seconds_sum{path='/get-random-number'}[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "HTTP request latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(sre_test_7_http_duration_seconds_sum{path='/get-random-number'}[1m]) / rate(sre_test_7_http_duration_seconds_count{path='/get-random-number'}[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Query engine timings",
   "type": "graph",
   "description": "Time spent in each mode, per second",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(sre_test_7_http_duration_seconds_sum{path='/get-random-number'}[1m])",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"golang\"}[1m])",
     "legendFormat": "Allocated"
    }
   ]
  }
 ]
}